== Medications Resource実装ガイド

このリソースは医師の処方箋、薬局での払い出し、薬剤投与、ワクチン接種状況についての情報を扱う。この文書ではこのリソースを利用して実際のサービスを実装するための方法について解説する。

=== 目的と範囲

この文書で扱うFHIR resourceは以下の4つである。

* Medication
* MedicationRequest
* MedicationDispense
* MedicationAdministration
* Immunization

HL7 FHIR R4のMedications resourceにはその他開発中のResourceがあるが、
現時点では上記のResourceを対象としている。

=== Medications Resource概説

先に述べたようにMedications resourceは処方に関連する情報モデルであり、日常的な診療情報とは以下のように対応する。

[options="header"]
.Table HL7 FHIR Medicatins Resource一覧
|===
|FHIR Resource|臨床概念

|Medication
|薬剤リスト

|MedicationRequest
|処方箋

|MedicationDispense
|薬剤払い出し(調剤結果)

|MedicationAdministration
|薬剤投与状況（注射記録、内服結果)

|===

Medicationは薬剤のリストであり、MedicationRequest, MedicationDispense, MedicationAdministrationに組み込まれて利用される。MedicationAdministration Resourceは最終的に患者にどのように薬剤が投与されたかの結果が記録される。したがって、内服処方であれば患者が内服した結果であり、注射であれば医療従事者による注射の実施記録となる。業務手順を示したシーケンス図を示す。

.Figure Medicationsシーケンス図（内服処方箋）
[plantuml]
--
医師 -> 薬剤師: MedicationRequest
薬剤師 -> 患者: MedicationDispense
--

.Figure Medicationsシーケンス図（内服処方箋）
[plantuml]
--
医師 -> 薬剤師: MedicationRequest
薬剤師 -> 看護師: MedicationDispense
看護師 -> 患者: MedicationAction
--

Immunizationはワクチン接種履歴についての記録である。以下、各Resourceについて解説する。


=== Medication
このResourceは単独で用いられることはなく、MedicationRequestやMedicationDispenseなど、他のResourceに組み込まれて利用される。

Medication ResourceのUML図を以下に示す。

.Figure Mecdication Resource UML図
[plantuml]
--
class "Medication(Domain Resource)" as Medication {
      identifier: Identifier [0..*]
      code: CodeableConcept [0..1]
      status: code [0..1]
      manufacturer: Reference [0..1]
      amount: Ratio [0..1]
}

class Batch {
      lotNumber: string [0..1]
      expirationDate: dateTime [0..1]
}
class Ingredient {
      item: Type [1..1]
      isActive: Boolean [0..1]
      strength: Type [0..1]
}
Medication "0..*" *-right- Batch : batch
Medication "0..*" *-down- Ingredient : ingredient
--

.XML template
[source,xml]
--
<Medication xmlns="http://hl7.org/fhir">
 <!-- from Resource: id, meta, implicitRules, and language -->
 <!-- from DomainResource: text, contained, extension, and modifierExtension -->
 <identifier><!-- 0..* Identifier Business identifier for this medication --></identifier>
 <code><!-- 0..1 CodeableConcept Codes that identify this medication --></code>
 <status value="[code]"/><!-- 0..1 active | inactive | entered-in-error -->
 <manufacturer><!-- 0..1 Reference(Organization) Manufacturer of the item --></manufacturer>
 <doseForm><!-- 0..1 CodeableConcept powder | tablets | capsule + --></doseForm>
 <amount><!-- 0..1 Ratio Amount of drug in package --></amount>
 <ingredient>  <!-- 0..* Active or inactive ingredient -->
  <item[x]><!-- 1..1 CodeableConcept|Reference(Medication|Substance) The actual ingredient or content --></item[x]>
  <isActive value="[boolean]"/><!-- 0..1 Active ingredient indicator -->
  <strength[x]><!-- 0..1 Ratio|CodeableConcept Quantity of ingredient present --></strength[x]>
 </ingredient>
 <batch>  <!-- 0..1 Details about packaged medications -->
  <lotNumber value="[string]"/><!-- 0..1 Identifier assigned to batch -->
  <expirationDate value="[dateTime]"/><!-- 0..1 When batch will expire -->
 </batch>
</Medication>
--
.JSON template
[source,json]
--
{
  "resourceType" : "Medication",
  // from Resource: id, meta, implicitRules, and language
  // from DomainResource: text, contained, extension, and modifierExtension
  "identifier" : [{ Identifier }], // Business identifier for this medication
  "code" : { CodeableConcept }, // Codes that identify this medication
  "status" : "<code>", // active | inactive | entered-in-error
  "manufacturer" : { Reference(Organization) }, // Manufacturer of the item
  "doseForm" : { CodeableConcept }, // powder | tablets | capsule +
  "amount" : { Ratio }, // Amount of drug in package
  "ingredient" : [{ // Active or inactive ingredient
    // item[x]: The actual ingredient or content. One of these 2:
    "itemCodeableConcept" : { CodeableConcept },
    "itemReference" : { Reference(Medication|Substance) },
    "isActive" : <boolean>, // Active ingredient indicator
    // strength[x]: Quantity of ingredient present. One of these 2:
    "strengthRatio" : { Ratio }
    "strengthCodeableConcept" : { CodeableConcept }
  }],
  "batch" : { // Details about packaged medications
    "lotNumber" : "<string>", // Identifier assigned to batch
    "expirationDate" : "<dateTime>" // When batch will expire
  }
}
--

==== Terminology bindings
薬剤コードとして、_HL7 FHIR_　<<FHIR_orig>>ではSNOMED CTが前提となっている。日本での使用を考え、以下のTerminologyを推奨とする。

.Table Terminology bindings
|===
|Path|定義|Type|Reference

|Medication.code|薬剤を定義するコード|Example|#HOTコード#

|Medication.status|その薬剤の有効性を示すコード|Required|Medication Status Codes
|Medication.doseForm|剤形についてのコード|Example|#改訂Merit9コード
|Medication.ingredientStrength|薬剤成分の力価を示すコード|Example|Medication Ingredient Strength Codes
|===



// .Table Medication Resource構造
// --
// |項目名|Flags|Cardinality|Type|内容、制約

// |Medication
// |TU
// |
// |DomainResource
// |Medication resouceの定義 +
// id, meta, implicitRules, language, text, contained, extension, modifiedExtension項目の定義は上位クラスで行っている。
// |===


=== MedicationRequest
このResourceは前述のように内服、注射を問わず処方箋についての情報を示している。

UML図を以下に示す。
.Figure MecdicationRequest Resource UML図
[plantuml]
--
class "MedicationRequest (DomainResource)" as MedicationRequest {
  identifier: Identifier [0..*]
  status: code [1..1] <<medicationrequestStatus!>>
  statusReason: CodeableConcept [0..1] <<medicationRequestStatus Reas...??>>
  intent: code [1..1] <<medicationRequest Intent!>>
  category: CodeableConcept [0..] <<medicationRequest Category ??>>
  priority: code [0..1] <<RequestPriority!>>
  doNotPerform: boolean [0..1]
  reported : boolean [0..1]
  informationSource : Reference [0..1] <<Patient|Practitioner| PractitionerRole|RelatedPerson|Organization>>
  medication[x]: Type [1..1] <<CodeableConcept|Reference(Medication); SNOMEDCTMedicationCodes??>>
  subject: Reference [1..1] <<Patient|Group>>
  encounter: Reference [0..1] <<Encounter>>
  supportingInformation: Reference [0..] <<Any>>
  authoredOn: dateTime [0..1]
  requester : Reference [0..1] <<Practitioner|PractitionerRole|Organization|Patient|RelatedPerson|Device>>
  performer: Reference [0..1] <<Practitioner|PractitionerRole|Organization|Patient|Device|RelatedPerson|CareTeam|HealthcareService>>
  performerType: CodeableConcept [0..1] <<ProcedurePerformerRoleCodes??>>
  recorder: Reference [0..1] <<Practitioner|PractitionerRole>>
  reasonCode: CodeableConcept [0..] <<Condition/Problem/DiagnosisCo...??>>
  reasonReference: Reference [0..] <<Condition|Observation>>
  instantiatesCanonical: canonical [0..] <<PlanDefinition|ActivityDefinition>>
  instantiatesUri: uri [0..]
  basedOn: Reference [0..] <<CarePlan|MedicationRequest|ServiceRequest|ImmunizationRecommendation>>
  groupIdentifier: Identifier [0..1]
  courseOfTherapyType : CodeableConcept [0..1] <<medicationRequest Course of T...??>>
  insurance: Reference [0..] <<Coverage|ClaimResponse>>
  note: Annotation [0..]
  dosageInstruction: Dosage [0..]
  priorPrescription: Reference [0..1] <<MedicationRequest>>
  detectedIssue: Reference [0..] <<DetectedIssue>>
  eventHistory: Reference [0..*] <<Provenance>>
}

class DispenseRequest {
  dispenseInterval: Duration [0..1]
  validityPeriod: Period [0..1]
  numberOfRepeatsAllowed: unsignedInt [0..1]
  quantity: Quantity(SimpleQuantity) [0..1]
  expectedSupplyDuration: Duration [0..1]
  performer: Reference [0..1] <<Organization>>
}

class InitialFill {
  quantity: Quantity(SimpleQuantity) [0..1]
  duration: Duration [0..1]
}

class Substitution {
  allowed[x]: Type [1..1] <<boolean|CodeableConcept; v3.ActSubstanceAdminSubstitut...??>>
  reason: CodeableConcept [0..1] <<v3.SubstanceAdminSubstitution...??>>
}

MedicationRequest *-- "0..1" DispenseRequest

DispenseRequest *-- "0..1" InitialFill

MedicationRequest *-- "0..1" Substitution
--

==== 項目解説
===== MedicationRequest
Element ID:: MedicationRequest
定義:: 薬剤を提供するためのオーダーと患者がどのように投与されるかについての指示についての情報。このResourceは、外来や入院の区別なく、ケアプランなどの業務フローでも利用できるように"MedicationPrescription"や"MedicationOrder"よりも"MedicationRequest"と呼ばれる。
Cardinality:: 0..*
Type:: DomainResource
別名:: Prescription, Order, 処方箋, 注射指示


===== MedicationRequest.identifier
Element ID:: MedicationRequest.identifier
内容:: この処方オーダーの識別子。業務
Cardinality:: 0..*
Type:: Identifier
Comments:: これは業務手順生成されたインスタンスの識別子であって、このResourceそのものの識別子ではない。

===== MedicationRequest.status
Element ID:: MedicationRequest.status
定義:: オーダーの現状を特定するコード。一般的には、この状態は"active"か"completed"であろう。
Cardinality:: 1..1
Terminology Binding:: Medicationrequest status (必須)
Type:: code
Is Modifier::	true (理由：このエレメントは、このリソースが適切に扱われるべきであることを意味している"entered-in-error"という状態も示すことがあるため、"modifier"とラベルされている）
Summary:: true
Comments:: このエレメントは、このリソースが適切に扱われるべきであることを意味する"entered-in-error"という状態も示すため、"modifier"とラベルされている。

===== MedicationRequest.statusReason
Element ID:: MedicationRequest.statusReason
定義::	MedicationRequestが現在の状態にある理由を記載する
Cardinality:: 0..1
Terminology Binding::  Medication request status reason codes (Example)
Type:: CodeableConcept
Comments:: このエレメントは、一般的には"suspended"(保留)や"canceled"(中止)のような"exception"(例外)のときだけに利用される。なぜこの MedicationRequest が作成されたかについての理由はこのエレメントではなく、 reasonCode に記載される。

===== MedicationRequest.intent
Element ID:: MedicationRequest.intent
定義:: このオーダーが、提案されたものか、計画されたもの、あるいは本来のオーダーであるのかを示す。
Cardinality:: 1..1
Terminology Binding:: Medication request intent (必須)
Type:: code
Is Modifier:: 	true (理由: このエレメントは全ての記述的属性の解釈を変えるものである。例えば、「発生するために推奨されたオーダーの時間」と「発生することが承認されたオーダーの時間」と「発生することが承認されたオーダーの時間」と「オーダーを発生するために誰が承認したか」）
Summary:: true
Comments:: requesterの種別は MedicationRequest の手順が異なれば制約を受けることが期待される。例えば、Proposal(提案)は患者(Patient)、関係者(reratedPerson)、医療従事者(Practitioner)や機器(Device)から生成されうる。もともともオーダーは医療従事者からのみ生成される。

オーダーのインスタンスはrequestかorderから生成され、MedicationAdministrationの記録としても転用される。

このエレメントは、このResourceが実際に、いつどのように適応できるのかをについて、その意図を変えることがあるため、 modifier としてラベルされている。

===== MedicationRequest.category
Element ID:: MedicationRequest.category
Definition:: この処方オーダーが実施あるいは管理される種別（例えば、入院処方、外来処方）を示す。
Terminology Binding:: 

Indicates the type of medication request (for example, where the medication is expected to be consumed or administered (i.e. inpatient or outpatient)).
Cardinality	0..*
Terminology Binding	Medication request category codes (Example)
Type	CodeableConcept
Comments	

The category can be used to include where the medication is expected to be consumed or other types of requests.
MedicationRequest.priority
Element Id	MedicationRequest.priority
Definition	

Indicates how quickly the Medication Request should be addressed with respect to other requests.
Cardinality	0..1
Terminology Binding	Request priority (Required)
Type	code
Summary	true
MedicationRequest.doNotPerform
Element Id	MedicationRequest.doNotPerform
Definition	

If true indicates that the provider is asking for the medication request not to occur.
Cardinality	0..1
Type	boolean
Is Modifier	true (Reason: This element is labeled as a modifier because this element negates the request to occur (ie, this is a request for the medication not to be ordered or prescribed, etc))
Summary	true
Comments	

If do not perform is not specified, the request is a positive request e.g. "do perform".
MedicationRequest.reported[x]
Element Id	MedicationRequest.reported[x]
Definition	

Indicates if this record was captured as a secondary 'reported' record rather than as an original primary source-of-truth record. It may also indicate the source of the report.
Cardinality	0..1
Type	boolean|Reference(Patient | Practitioner | PractitionerRole | RelatedPerson | Organization)
[x] Note	See Choice of Data Types for further information about how to use [x]
Summary	true
MedicationRequest.medication[x]
Element Id	MedicationRequest.medication[x]
Definition	

Identifies the medication being requested. This is a link to a resource that represents the medication which may be the details of the medication or simply an attribute carrying a code that identifies the medication from a known list of medications.
Cardinality	1..1
Terminology Binding	SNOMED CT Medication Codes (Example)
Type	CodeableConcept|Reference(Medication)
[x] Note	See Choice of Data Types for further information about how to use [x]
Summary	true
Comments	

If only a code is specified, then it needs to be a code for a specific product. If more information is required, then the use of the Medication resource is recommended. For example, if you require form or lot number or if the medication is compounded or extemporaneously prepared, then you must reference the Medication resource.
MedicationRequest.subject
Element Id	MedicationRequest.subject
Definition	

A link to a resource representing the person or set of individuals to whom the medication will be given.
Cardinality	1..1
Type	Reference(Patient | Group)
Summary	true
Comments	

The subject on a medication request is mandatory. For the secondary use case where the actual subject is not provided, there still must be an anonymized subject specified.
MedicationRequest.encounter
Element Id	MedicationRequest.encounter
Definition	

The Encounter during which this [x] was created or to which the creation of this record is tightly associated.
Cardinality	0..1
Type	Reference(Encounter)
Comments	

This will typically be the encounter the event occurred within, but some activities may be initiated prior to or after the official completion of an encounter but still be tied to the context of the encounter." If there is a need to link to episodes of care they will be handled with an extension.
MedicationRequest.supportingInformation
Element Id	MedicationRequest.supportingInformation
Definition	

Include additional information (for example, patient height and weight) that supports the ordering of the medication.
Cardinality	0..*
Type	Reference(Any)
MedicationRequest.authoredOn
Element Id	MedicationRequest.authoredOn
Definition	

The date (and perhaps time) when the prescription was initially written or authored on.
Cardinality	0..1
Type	dateTime
Summary	true
MedicationRequest.requester
Element Id	MedicationRequest.requester
Definition	

The individual, organization, or device that initiated the request and has responsibility for its activation.
Cardinality	0..1
Type	Reference(Practitioner | PractitionerRole | Organization | Patient | RelatedPerson | Device)
Summary	true
MedicationRequest.performer
Element Id	MedicationRequest.performer
Definition	

The specified desired performer of the medication treatment (e.g. the performer of the medication administration).
Cardinality	0..1
Type	Reference(Practitioner | PractitionerRole | Organization | Patient | Device | RelatedPerson | CareTeam)
MedicationRequest.performerType
Element Id	MedicationRequest.performerType
Definition	

Indicates the type of performer of the administration of the medication.
Cardinality	0..1
Terminology Binding	Procedure Performer Role Codes (Example)
Type	CodeableConcept
Summary	true
Comments	

If specified without indicating a performer, this indicates that the performer must be of the specified type. If specified with a performer then it indicates the requirements of the performer if the designated performer is not available.
MedicationRequest.recorder
Element Id	MedicationRequest.recorder
Definition	

The person who entered the order on behalf of another individual for example in the case of a verbal or a telephone order.
Cardinality	0..1
Type	Reference(Practitioner | PractitionerRole)
MedicationRequest.reasonCode
Element Id	MedicationRequest.reasonCode
Definition	

The reason or the indication for ordering or not ordering the medication.
Cardinality	0..*
Terminology Binding	Condition/Problem/Diagnosis Codes (Example)
Type	CodeableConcept
Comments	

This could be a diagnosis code. If a full condition record exists or additional detail is needed, use reasonReference.
MedicationRequest.reasonReference
Element Id	MedicationRequest.reasonReference
Definition	

Condition or observation that supports why the medication was ordered.
Cardinality	0..*
Type	Reference(Condition | Observation)
Comments	

This is a reference to a condition or observation that is the reason for the medication order. If only a code exists, use reasonCode.
MedicationRequest.instantiatesCanonical
Element Id	MedicationRequest.instantiatesCanonical
Definition	

The URL pointing to a protocol, guideline, orderset, or other definition that is adhered to in whole or in part by this MedicationRequest.
Cardinality	0..*
Type	canonical
Summary	true
MedicationRequest.instantiatesUri
Element Id	MedicationRequest.instantiatesUri
Definition	

The URL pointing to an externally maintained protocol, guideline, orderset or other definition that is adhered to in whole or in part by this MedicationRequest.
Cardinality	0..*
Type	uri
Summary	true
MedicationRequest.basedOn
Element Id	MedicationRequest.basedOn
Definition	

A plan or request that is fulfilled in whole or in part by this medication request.
Cardinality	0..*
Type	Reference(CarePlan | MedicationRequest | ServiceRequest | ImmunizationRecommendation)
Summary	true
MedicationRequest.groupIdentifier
Element Id	MedicationRequest.groupIdentifier
Definition	

A shared identifier common to all requests that were authorized more or less simultaneously by a single author, representing the identifier of the requisition or prescription.
Cardinality	0..1
Type	Identifier
Requirements	

Requests are linked either by a "basedOn" relationship (i.e. one request is fulfilling another) or by having a common requisition. Requests that are part of the same requisition are generally treated independently from the perspective of changing their state or maintaining them after initial creation.
Summary	true
MedicationRequest.courseOfTherapyType
Element Id	MedicationRequest.courseOfTherapyType
Definition	

The description of the overall patte3rn of the administration of the medication to the patient.
Cardinality	0..1
Terminology Binding	Medication request course of therapy codes (Example)
Type	CodeableConcept
Comments	

This attribute should not be confused with the protocol of the medication.
MedicationRequest.insurance
Element Id	MedicationRequest.insurance
Definition	

Insurance plans, coverage extensions, pre-authorizations and/or pre-determinations that may be required for delivering the requested service.
Cardinality	0..*
Type	Reference(Coverage | ClaimResponse)
MedicationRequest.note
Element Id	MedicationRequest.note
Definition	

Extra information about the prescription that could not be conveyed by the other attributes.
Cardinality	0..*
Type	Annotation
MedicationRequest.dosageInstruction
Element Id	MedicationRequest.dosageInstruction
Definition	

Indicates how the medication is to be used by the patient.
Cardinality	0..*
Type	Dosage
Comments	

There are examples where a medication request may include the option of an oral dose or an Intravenous or Intramuscular dose. For example, "Ondansetron 8mg orally or IV twice a day as needed for nausea" or "Compazine® (prochlorperazine) 5-10mg PO or 25mg PR bid prn nausea or vomiting". In these cases, two medication requests would be created that could be grouped together. The decision on which dose and route of administration to use is based on the patient's condition at the time the dose is needed.
MedicationRequest.dispenseRequest
Element Id	MedicationRequest.dispenseRequest
Definition	

Indicates the specific details for the dispense or medication supply part of a medication request (also known as a Medication Prescription or Medication Order). Note that this information is not always sent with the order. There may be in some settings (e.g. hospitals) institutional or system support for completing the dispense details in the pharmacy department.
Cardinality	0..1
MedicationRequest.dispenseRequest.initialFill
Element Id	MedicationRequest.dispenseRequest.initialFill
Definition	

Indicates the quantity or duration for the first dispense of the medication.
Cardinality	0..1
Comments	

If populating this element, either the quantity or the duration must be included.
MedicationRequest.dispenseRequest.initialFill.quantity
Element Id	MedicationRequest.dispenseRequest.initialFill.quantity
Definition	

The amount or quantity to provide as part of the first dispense.
Cardinality	0..1
Type	SimpleQuantity
MedicationRequest.dispenseRequest.initialFill.duration
Element Id	MedicationRequest.dispenseRequest.initialFill.duration
Definition	

The length of time that the first dispense is expected to last.
Cardinality	0..1
Type	Duration
MedicationRequest.dispenseRequest.dispenseInterval
Element Id	MedicationRequest.dispenseRequest.dispenseInterval
Definition	

The minimum period of time that must occur between dispenses of the medication.
Cardinality	0..1
Type	Duration
MedicationRequest.dispenseRequest.validityPeriod
Element Id	MedicationRequest.dispenseRequest.validityPeriod
Definition	

This indicates the validity period of a prescription (stale dating the Prescription).
Cardinality	0..1
Type	Period
Requirements	

Indicates when the Prescription becomes valid, and when it ceases to be a dispensable Prescription.
Comments	

It reflects the prescribers' perspective for the validity of the prescription. Dispenses must not be made against the prescription outside of this period. The lower-bound of the Dispensing Window signifies the earliest date that the prescription can be filled for the first time. If an upper-bound is not specified then the Prescription is open-ended or will default to a stale-date based on regulations.
MedicationRequest.dispenseRequest.numberOfRepeatsAllowed
Element Id	MedicationRequest.dispenseRequest.numberOfRepeatsAllowed
Definition	

An integer indicating the number of times, in addition to the original dispense, (aka refills or repeats) that the patient can receive the prescribed medication. Usage Notes: This integer does not include the original order dispense. This means that if an order indicates dispense 30 tablets plus "3 repeats", then the order can be dispensed a total of 4 times and the patient can receive a total of 120 tablets. A prescriber may explicitly say that zero refills are permitted after the initial dispense.
Cardinality	0..1
Type	unsignedInt
Comments	

If displaying "number of authorized fills", add 1 to this number.
MedicationRequest.dispenseRequest.quantity
Element Id	MedicationRequest.dispenseRequest.quantity
Definition	

The amount that is to be dispensed for one fill.
Cardinality	0..1
Type	SimpleQuantity
MedicationRequest.dispenseRequest.expectedSupplyDuration
Element Id	MedicationRequest.dispenseRequest.expectedSupplyDuration
Definition	

Identifies the period time over which the supplied product is expected to be used, or the length of time the dispense is expected to last.
Cardinality	0..1
Type	Duration
Comments	

In some situations, this attribute may be used instead of quantity to identify the amount supplied by how long it is expected to last, rather than the physical quantity issued, e.g. 90 days supply of medication (based on an ordered dosage). When possible, it is always better to specify quantity, as this tends to be more precise. expectedSupplyDuration will always be an estimate that can be influenced by external factors.
MedicationRequest.dispenseRequest.performer
Element Id	MedicationRequest.dispenseRequest.performer
Definition	

Indicates the intended dispensing Organization specified by the prescriber.
Cardinality	0..1
Type	Reference(Organization)
MedicationRequest.substitution
Element Id	MedicationRequest.substitution
Definition	

Indicates whether or not substitution can or should be part of the dispense. In some cases, substitution must happen, in other cases substitution must not happen. This block explains the prescriber's intent. If nothing is specified substitution may be done.
Cardinality	0..1
MedicationRequest.substitution.allowed[x]
Element Id	MedicationRequest.substitution.allowed[x]
Definition	

True if the prescriber allows a different drug to be dispensed from what was prescribed.
Cardinality	1..1
Terminology Binding	V3 Value SetActSubstanceAdminSubstitutionCode (Example)
Type	boolean|CodeableConcept
[x] Note	See Choice of Data Types for further information about how to use [x]
Comments	

This element is labeled as a modifier because whether substitution is allow or not, it cannot be ignored.
MedicationRequest.substitution.reason
Element Id	MedicationRequest.substitution.reason
Definition	

Indicates the reason for the substitution, or why substitution must or must not be performed.
Cardinality	0..1
Terminology Binding	V3 Value SetSubstanceAdminSubstitutionReason (Example)
Type	CodeableConcept
MedicationRequest.priorPrescription
Element Id	MedicationRequest.priorPrescription
Definition	

A link to a resource representing an earlier order related order or prescription.
Cardinality	0..1
Type	Reference(MedicationRequest)
MedicationRequest.detectedIssue
Element Id	MedicationRequest.detectedIssue
Definition	

Indicates an actual or potential clinical issue with or between one or more active or proposed clinical actions for a patient; e.g. Drug-drug interaction, duplicate therapy, dosage alert etc.
Cardinality	0..*
Type	Reference(DetectedIssue)
Alternate Names	Contraindication; Drug Utilization Review (DUR); Alert
Comments	

This element can include a detected issue that has been identified either by a decision support system or by a clinician and may include information on the steps that were taken to address the issue.
MedicationRequest.eventHistory
Element Id	MedicationRequest.eventHistory
Definition	

Links to Provenance records for past versions of this resource or fulfilling request or event resources that identify key state transitions or updates that are likely to be relevant to a user looking at the current version of the resource.
Cardinality	0..*
Type	Reference(Provenance)
Comments	

This might not include provenances for all versions of the request – only those deemed “relevant” or important. This SHALL NOT include the provenance associated with this current version of the resource. (If that provenance is deemed to be a “relevant” change, it will need to be added as part of a later update. Until then, it can be queried directly as the provenance that points to this version using _revinclude All Provenances should have some historical version of this Request as their subject.).

