== 文書翻訳

この文書では、FHIRに関連する文書の翻訳について概説する。

HL7 FHIR-JPワーキンググループではFHIRの理解を深めていくために一部で翻
訳を試みている。

効率よく翻訳を進めていくためには、用語集の整備やツールの活用が欠かせな
い。翻訳用語の調整には全体での議論も必要である。ここでは、Google
translator toolkitを使った翻訳の進め方、用語集(Glossary)の整備について概説する。

=== 目的と範囲

FHIRに関連する文書を日本語に翻訳するために必要となることを対象とする。Google translator toolkitを使って翻訳することを推奨する。内容は文体についてのガイドラインと翻訳の方針につい
てslackで話し合ったことを中心にまとめたものである。

検討の後に公開していくことを前提としている。

=== 翻訳した文書

以下の翻訳はFHIR-JPワーキンググループのSWG5で有志により翻訳されたもの
であり、日本HL7協会とは何ら関係なく公式なものでもない。正確な情報につ
いては原文を参照すること。

なお、FHIR Implementation GuideはHL7が著作権を有する文書であり、日本
HL7協会の木村通男会長の許諾を得て翻訳・公開するものである。しかし、公式な翻
訳ではなく、同団体の見解を代表するものでもない。

* link:translations/FHIR_Implementation_guide.html[FHIR Implementation Guide]
* link:translations/HL7_FHIR_Medications_modules.html[Medication Modules]
* link:translations/HL7_FHIR_Medication_Resource.html[Medication Resource]
* link:translations/HL7_FHIR_MedicationRequest_resource.html[MedicationRequest Resource]

// * link:translations/condition-definitions_aoki.html[Condition Definitions]
// * link:translations/allergyintolerance-definitions.html[Allergy Intolerance Definition]
// * link:translations/procedure-definitions.html[Procedure Definitions]

=== 翻訳の方針
* 最初から完璧なものは目指さない
* 「です・ます」調。
* templateの中の英語は訳さない
* Resource, Profile, ExtensionなどのFHIR用語は翻訳しない

=== Glossary


