== Medications Resource実装ガイド

このリソースは医師の処方箋、薬局での払い出し、薬剤投与、ワクチン接種状況についての情報を扱う。この文書ではこのリソースを利用して実際のサービスを実装するための方法について解説する。

=== 目的と範囲

この文書で扱うFHIR resourceは以下の4つである。

* Medication
* MedicationRequest
* MedicationDispense
* MedicationAdministration
* Immunization

HL7 FHIR R4のMedications resourceにはその他開発中のResourceがあるが、
現時点では上記のResourceを対象としている。

=== Medications Resource概説

先に述べたようにMedications resourceは処方に関連する情報モデルであり、日常的な診療情報とは以下のように対応する。

[options="header"]
.Table HL7 FHIR Medicatins Resource一覧
|===
|FHIR Resource|臨床概念

|Medication
|薬剤リスト

|MedicationRequest
|処方箋

|MedicationDispense
|薬剤払い出し(調剤結果)

|MedicationAdministration
|薬剤投与状況（注射記録、内服結果)

|===

Medicationは薬剤のリストであり、MedicationRequest, MedicationDispense, MedicationAdministrationに組み込まれて利用される。MedicationAdministration Resourceは最終的に患者にどのように薬剤が投与されたかの結果が記録される。したがって、内服処方であれば患者が内服した結果であり、注射であれば医療従事者による注射の実施記録となる。業務手順を示したシーケンス図を示す。

.Figure Medicationsシーケンス図（内服処方箋)
[plantuml]
--
医師 -> 薬剤師: MedicationRequest
薬剤師 -> 患者: MedicationDispense
--

.Figure Medicationsシーケンス図（内服処方箋)
[plantuml]
--
医師 -> 薬剤師: MedicationRequest
薬剤師 -> 看護師: MedicationDispense
看護師 -> 患者: MedicationAction
--

Immunizationはワクチン接種履歴についての記録である。

以下、それぞれのリソースの実装について解説する。

=== Medication
このResourceは単独で用いられることはなく、MedicationRequestやMedicationDispenseなどの他のResourceに組み込まれて利用される。

Medication ResourceのUML図を以下に示す。

.Figure Mecdication Resource UML図
[plantuml]
--
class "Medication(Domain Resource)" as Medication {
      identifier: Identifier [0..*]
      code: CodeableConcept [0..1]
      status: code [0..1]
      manufacturer: Reference [0..1]
      amount: Ratio [0..1]
}

class Batch {
      lotNumber: string [0..1]
      expirationDate: dateTime [0..1]
}
class Ingredient {
      item: Type [1..1]
      isActive: Boolean [0..1]
      strength: Type [0..1]
}
Medication "0..*" *-right- Batch : batch
Medication "0..*" *-down- Ingredient : ingredient
--

.XML template
[source,xml]
--
<Medication xmlns="http://hl7.org/fhir">
 <!-- from Resource: id, meta, implicitRules, and language -->
 <!-- from DomainResource: text, contained, extension, and modifierExtension -->
 <identifier><!-- 0..* Identifier Business identifier for this medication --></identifier>
 <code><!-- 0..1 CodeableConcept Codes that identify this medication --></code>
 <status value="[code]"/><!-- 0..1 active | inactive | entered-in-error -->
 <manufacturer><!-- 0..1 Reference(Organization) Manufacturer of the item --></manufacturer>
 <doseForm><!-- 0..1 CodeableConcept powder | tablets | capsule + --></doseForm>
 <amount><!-- 0..1 Ratio Amount of drug in package --></amount>
 <ingredient>  <!-- 0..* Active or inactive ingredient -->
  <item[x]><!-- 1..1 CodeableConcept|Reference(Medication|Substance) The actual ingredient or content --></item[x]>
  <isActive value="[boolean]"/><!-- 0..1 Active ingredient indicator -->
  <strength[x]><!-- 0..1 Ratio|CodeableConcept Quantity of ingredient present --></strength[x]>
 </ingredient>
 <batch>  <!-- 0..1 Details about packaged medications -->
  <lotNumber value="[string]"/><!-- 0..1 Identifier assigned to batch -->
  <expirationDate value="[dateTime]"/><!-- 0..1 When batch will expire -->
 </batch>
</Medication>
--
.JSON template
[source,json]
--
{
  "resourceType" : "Medication",
  // from Resource: id, meta, implicitRules, and language
  // from DomainResource: text, contained, extension, and modifierExtension
  "identifier" : [{ Identifier }], // Business identifier for this medication
  "code" : { CodeableConcept }, // Codes that identify this medication
  "status" : "<code>", // active | inactive | entered-in-error
  "manufacturer" : { Reference(Organization) }, // Manufacturer of the item
  "doseForm" : { CodeableConcept }, // powder | tablets | capsule +
  "amount" : { Ratio }, // Amount of drug in package
  "ingredient" : [{ // Active or inactive ingredient
    // item[x]: The actual ingredient or content. One of these 2:
    "itemCodeableConcept" : { CodeableConcept },
    "itemReference" : { Reference(Medication|Substance) },
    "isActive" : <boolean>, // Active ingredient indicator
    // strength[x]: Quantity of ingredient present. One of these 2:
    "strengthRatio" : { Ratio }
    "strengthCodeableConcept" : { CodeableConcept }
  }],
  "batch" : { // Details about packaged medications
    "lotNumber" : "<string>", // Identifier assigned to batch
    "expirationDate" : "<dateTime>" // When batch will expire
  }
}
--

==== Terminology bindings
薬剤コードとして、_HL7 FHIR_　<<FHIR_orig>>ではSNOMED CTなどのコードが前提となっているが、薬剤サブワーキンググループおよびのVocabularyサブワーキンググループの見解として以下のTerminologyを推奨とする。

.Table Terminology bindings
|===
|Path|定義|Type|Reference

|Medication.code|薬剤を定義するコード|Example|#HOTコード#

|Medication.status|その薬剤の有効性を示すコード|Required|Medication Status Codes
|Medication.doseForm|剤形についてのコード|Example|#TBD#
|Medication.ingredientStrength|薬剤成分の力価を示すコード|Example|Medication Ingredient Strength Codes
|===



// .Table Medication Resource構造
// --
// |項目名|Flags|Cardinality|Type|内容、制約

// |Medication
// |TU
// |
// |DomainResource
// |Medication resouceの定義 +
// id, meta, implicitRules, language, text, contained, extension, modifiedExtension項目の定義は上位クラスで行っている。
// |===


=== MedicationRequest
このResourceは前述のように内服、注射を問わず処方箋についての情報を示している。

UML図を以下に示す。
.Figure MecdicationRequest Resource UML図
[plantuml]
--
class "MedicationRequest (DomainResource)" as MedicationRequest {
  identifier: Identifier [0..*]
  status: code [1..1] <<medicationrequestStatus!>>
  statusReason: CodeableConcept [0..1] <<medicationRequestStatus Reas...??>>
  intent: code [1..1] <<medicationRequest Intent!>>
  category: CodeableConcept [0..] <<medicationRequest Category ??>>
  priority: code [0..1] <<RequestPriority!>>
  doNotPerform: boolean [0..1]
  reported : boolean [0..1]
  informationSource : Reference [0..1] <<Patient|Practitioner| PractitionerRole|RelatedPerson|Organization>>
  medication[x]: Type [1..1] <<CodeableConcept|Reference(Medication); SNOMEDCTMedicationCodes??>>
  subject: Reference [1..1] <<Patient|Group>>
  encounter: Reference [0..1] <<Encounter>>
  supportingInformation: Reference [0..] <<Any>>
  authoredOn: dateTime [0..1]
  requester : Reference [0..1] <<Practitioner|PractitionerRole|Organization|Patient|RelatedPerson|Device>>
  performer: Reference [0..1] <<Practitioner|PractitionerRole|Organization|Patient|Device|RelatedPerson|CareTeam|HealthcareService>>
  performerType: CodeableConcept [0..1] <<ProcedurePerformerRoleCodes??>>
  recorder: Reference [0..1] <<Practitioner|PractitionerRole>>
  reasonCode: CodeableConcept [0..] <<Condition/Problem/DiagnosisCo...??>>
  reasonReference: Reference [0..] <<Condition|Observation>>
  instantiatesCanonical: canonical [0..] <<PlanDefinition|ActivityDefinition>>
  instantiatesUri: uri [0..]
  basedOn: Reference [0..] <<CarePlan|MedicationRequest|ServiceRequest|ImmunizationRecommendation>>
  groupIdentifier: Identifier [0..1]
  courseOfTherapyType : CodeableConcept [0..1] <<medicationRequest Course of T...??>>
  insurance: Reference [0..] <<Coverage|ClaimResponse>>
  note: Annotation [0..]
  dosageInstruction: Dosage [0..]
  priorPrescription: Reference [0..1] <<MedicationRequest>>
  detectedIssue: Reference [0..] <<DetectedIssue>>
  eventHistory: Reference [0..*] <<Provenance>>
}

class DispenseRequest {
  dispenseInterval: Duration [0..1]
  validityPeriod: Period [0..1]
  numberOfRepeatsAllowed: unsignedInt [0..1]
  quantity: Quantity(SimpleQuantity) [0..1]
  expectedSupplyDuration: Duration [0..1]
  performer: Reference [0..1] <<Organization>>
}

class InitialFill {
  quantity: Quantity(SimpleQuantity) [0..1]
  duration: Duration [0..1]
}

class Substitution {
  allowed[x]: Type [1..1] <<boolean|CodeableConcept; v3.ActSubstanceAdminSubstitut...??>>
  reason: CodeableConcept [0..1] <<v3.SubstanceAdminSubstitution...??>>
}

MedicationRequest *-- "0..1" DispenseRequest
DispenseRequest *-- "0..1" InitialFill
MedicationRequest *-- "0..1" Substitution
--

