language: ruby

rvm:
  - 2.6
jdk:
  - openjdk8

before_install:
  - sudo apt-get install plantuml

env:
  - URL=https://github.com/redpen-cc/redpen/releases/download/redpen-1.10.1

install:
  - wget $URL/redpen-1.10.1.tar.gz
  - tar xvf redpen-1.10.1.tar.gz
  - export PATH=$PATH:$PWD/redpen-distribution-1.10.1/bin

script:
  - gem install asciidoctor
  - gem install coderay
  - gem install asciidoctor-diagram