language: ruby

rvm:
  - 2.6
jdk:
  - openjdk8

before_install:
  - openssl aes-256-cbc -K $encrypted_b38bd137997e_key -iv $encrypted_b38bd137997e_iv -in etc/deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - git config --global user.name "skoba@Travis-CI"
  - git config --global user.email "skoba-github@travis-ci.org"
  - gem install bundler

env:
  - URL=https://github.com/redpen-cc/redpen/releases/download/redpen-1.10.1

install:
  - sudo apt-get install plantuml
  - wget $URL/redpen-1.10.1.tar.gz
  - tar xvf redpen-1.10.1.tar.gz
  - export PATH=$PATH:$PWD/redpen-distribution-1.10.1/bin
  - bundle install

script:
  - rake redpen
  - rake html
  - '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && git commit -m "Publishing site on `date "+%Y-%m-%d %H:%M:%S"`"