source 'https://rubygems.org'

gem 'rspec'
gem 'rake'
gem 'nokogiri'
gem 'coderay'
gem 'asciidoctor'
gem 'asciidoctor-diagram'
gem 'json_schemer'
gem 'ruby-hl7', git: 'https://github.com/skoba/ruby-hl7.git', branch: 'update_rdoc'
gem 'fhir_models'
#gem 'erubis'
