source 'https://rubygems.org'

gem 'rspec'
gem 'rake'
gem 'nokogiri'
gem 'coderay'
gem 'asciidoctor'
gem 'asciidoctor-diagram'
gem 'json_schemer'
gem 'ruby-hl7', '1.3.0'
gem 'fhir_models'
#gem 'erubis'
